"""
Concatenate every migration into one runnable file: schema_full.sql.

    python build_schema.py

Run it after adding a migration, so the consolidated file stays in step.

Writes OUTSIDE migrations/ deliberately: migrate.py globs migrations/*.sql, so a
copy of the whole schema living there would be picked up as the next migration
and replay everything.

The tracking rows migrate.py would have written are appended with the real
checksums, so a database built from the consolidated file is indistinguishable
from one built migration by migration - `migrate.py --status` shows them all
applied and has nothing to do.
"""

import hashlib
import pathlib

HERE = pathlib.Path(__file__).parent
MIGRATIONS = HERE / "migrations"
OUT = HERE / "schema_full.sql"

HEADER = """\
-- =============================================================================
-- KLASSER AI - COMPLETE SCHEMA
--
-- Every migration, in order, as one file. Generated by build_schema.py - do not
-- edit by hand; edit the migration and regenerate.
--
-- This is NOT in migrations/ on purpose: migrate.py runs every .sql file in
-- that directory, so a copy of the whole schema living there would be applied
-- as a further migration and replay everything.
--
-- Use it to stand up a fresh database in one step - a new Supabase project,
-- production, or a throwaway copy for testing:
--
--     psql "$DATABASE_URL" -f schema_full.sql
--
-- or paste it into the Supabase SQL editor. It ends by recording every
-- migration as applied, so `python migrate.py` afterwards correctly reports
-- nothing pending.
--
-- For an EXISTING database, use migrate.py instead. Running this file over one
-- that already has data is not safe: the CREATE TABLE statements are
-- IF NOT EXISTS, but the seed and ALTER statements are not all idempotent.
--
-- Contents:
{contents}
-- =============================================================================


"""

FOOTER = """

-- =============================================================================
-- Migration bookkeeping
--
-- Records what migrate.py would have recorded, with the same checksums, so this
-- file and the incremental path leave the database in the same state.
-- =============================================================================

CREATE TABLE IF NOT EXISTS schema_migrations (
    filename    TEXT PRIMARY KEY,
    checksum    TEXT NOT NULL,
    applied_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO schema_migrations (filename, checksum) VALUES
{rows}
ON CONFLICT (filename) DO NOTHING;
"""


def main() -> None:
    files = sorted(MIGRATIONS.glob("*.sql"))
    if not files:
        raise SystemExit(f"no migrations found in {MIGRATIONS}")

    contents = "\n".join(
        f"--   {i:>2}. {p.name:<28} "
        f"{len(p.read_text(encoding='utf-8').splitlines()):>4} lines"
        for i, p in enumerate(files, 1))

    parts = [HEADER.format(contents=contents)]
    rows = []

    for path in files:
        digest = hashlib.sha256(path.read_bytes()).hexdigest()[:16]
        rows.append(f"    ('{path.name}', '{digest}')")

        rule = "-- " + "=" * 76
        parts.append(f"\n\n{rule}\n-- {path.name}\n{rule}\n\n"
                     + path.read_text(encoding="utf-8").rstrip() + "\n")

    parts.append(FOOTER.format(rows=",\n".join(rows)))

    # newline="\n" and no BOM: this file is read by psql and by the Supabase SQL
    # editor, and Windows line endings plus a BOM have broken both before.
    OUT.write_text("".join(parts), encoding="utf-8", newline="\n")

    lines = len(OUT.read_text(encoding="utf-8").splitlines())
    print(f"wrote {OUT.name}: {len(files)} migrations, {lines} lines, "
          f"{OUT.stat().st_size / 1024:.1f} KB")


if __name__ == "__main__":
    main()
